version: '3'

services:

  pdf-converter-service:
    container_name: pdf-service
    image: mishastoma/pdfconverter:latest
    ports:
      - "8081:8081"
    depends_on:
      - activemq

  mail-service:
    container_name: mail-service
    image: mishastoma/mailnotifier:latest
    ports:
      - "8082:8082"

  main-app:
    container_name: main-app
    image: mishastoma/marketservice:latest
    ports:
      - "8090:8090"
    networks:
      - main-network
    depends_on:
      - keycloak
      - mail-service

  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: keycloak_db,application_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - main-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev --import-realm
    ports:
      - "8180:8180"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - main-network
    depends_on:
      - postgres

  activemq:
    container_name: activemq-broker
    image: rmohr/activemq:5.10.0
    ports:
      - "61616:61616"
      - "8161:8161"

networks:
  main-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local